apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-user>/helm-gitops-demo.git
    targetRevision: main
    path: charts/myapp
    helm:
      valueFiles:
        - ../../envs/prod/values-prod.yaml    #relative to source.path
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
